apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RawNENF/lakehouse.git   # <-- change this
    targetRevision: main
    path: apps/trino/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: lakehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
